language: dart
dart:
  - beta

sudo: required
env:
- TEST_VALUE=1 TEST_BOOL=true TEST_DB_ENV_VAR=postgres://user:password@host:5432/dbname
script:
- pub run test -j 1 -r expanded
- dart tool/runtime_test_runner.dart
branches:
  only:
    - master
